#!/bin/bash
#
# StatsD
#
# chkconfig: 3 50 50
# description: StatsD init.d
. /etc/rc.d/init.d/functions

DESC="azure-sb-statsd"
NAME="azure-sb-statsd"
DAEMON="/usr/local/sbin/azure-sb-statsd"
pidfile=/var/run/azure-sb-statsd.pid
lockfile=/var/lock/subsys/azure-sb-statsd
RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Determine if we can use the -p option to daemon, killproc, and status.
# RHEL < 5 can't.
if status | grep -q -- '-p' 2>/dev/null; then
    daemonopts="--pidfile $pidfile"
    pidopts="-p $pidfile"
fi

start() {
  echo -n $"Starting $NAME: "
  # See if it's already running. Look *only* at the pid file.
  if [ -f ${pidfile} ]; then
    failure "PID file exists for azure-sb-statsd"
    RETVAL=1
  else
    # Run as process
    $DAEMON ${AZUREJS} ${AZURE_CONFIG_DIR} ${AZURE_LOGFILE} &
    RETVAL=$?
    # Store PID
    echo $! > ${pidfile}

    # Success
    [ $RETVAL = 0 ] && success "azure-sb-statsd started"
  fi

  echo
  return $RETVAL
}

stop() {
  echo -n $"Stopping $NAME: "
  killproc -p ${pidfile}
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && rm -f ${pidfile}
}

# See how we were called.
case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  status)
  status -p ${pidfile} ${prog}
  RETVAL=$?
  ;;
  restart)
  stop
  start
  ;;
  condrestart)
  if [ -f ${pidfile} ] ; then
    stop
    start
  fi
  ;;
  *)
  echo $"Usage: $prog {start|stop|restart|condrestart|status}"
  exit 1
esac

exit $RETVAL
